"""Add deadline and priority to Todo model

Revision ID: fbc874e2f193
Revises: 4b10ab97282d
Create Date: 2025-09-09 19:25:09.937588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc874e2f193'
down_revision = '4b10ab97282d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###
